<?xml version="1.0"?>
<package format="2">
  <name>gom_xarm_bridge</name>
  <version>0.1.0</version>
  <description>TCP bridge between GOM Inspect CSV export and xArm move_line service</description>
  <maintainer email="joaquinrog06@gmail.com">joaquinrog</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>xarm_msgs</exec_depend>
</package>
